### ISSUE TITLE
Inworld AI Unity SDK with Oculus integration SDK throws build issue 

### ISSUE THREAD

**Issue by ganeshh-kumar** [inworld-ai/inworld-unity-sdk#86]
We are facing issues when trying to build the project for the Android platform when it has both the Inworld Unity SDK and the Oculus Integration SDK installed in it. We are getting the following error. Could you please help us find a solution for it?

<img width="988" alt="Screenshot 2023-07-26 024412" src="https://github.com/inworld-ai/inworld-unity-sdk/assets/104882657/dc7ed9cf-92d4-488a-b2d4-776ca39e0df1">

Platform/Editor/SDK Details:
Unity Editor - 2022.3.5f1
Oculus Integration SDK - v55.0
Inworld Unity SDK - v2.1.10

**Comment by ganeshh-kumar** [comment]
Unity Editor - 2022.3.5f1
Oculus Integration SDK - v55.0
Inworld Unity SDK - v2.1.10

**Comment by Div-Inworld** [comment]
hi @ganeshh-kumar 
We had resolved this issue in the release 2.1.8 . Are you able to update you Inworld Unity SDK to the latest release?
https://github.com/inworld-ai/inworld-unity-sdk/releases/tag/2.1.9

**Comment by Juniverse** [comment]
Hello, this is mainly because GLTFUtility's incompatiblity issue. Are you guys using ready player me avatars? If so, please try the followings:
1. delete the folder `Assets > Inworld.AI > Plugins > NewtonSoftJson`
![image](https://github.com/inworld-ai/inworld-unity-sdk/assets/68676221/d93be158-4a7b-4d50-9e64-187070f541a3)

2. Add `com.unity.nuget.newtonsoft-json@3.2` in your package manager.

**Comment by ganeshh-kumar** [comment]
It worked. Thank you so much for providing a fix for the issue.
